name: Push Issues to Global Project

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add Issue to User Project #2
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/brgjr10/projects/2
          github-token: ${{ secrets.GLOBAL_PROJECT_TOKEN }}
